name: cmeutils
channels:
  - conda-forge
dependencies:
  - freud >=2.13.1
  - fresnel >=0.13.5
  - gsd >=3.0
  - hoomd >=4.0
  - mbuild >=0.16.4
  - numpy
  - pip
  - python >= 3.10
  - matplotlib
  - pymbar >= 4.0
  - rowan
