name: cmeutils
channels:
  - conda-forge
dependencies:
  - fresnel
  - freud>=2.13.1
  - gsd>=3.0
  - hoomd<4.0=*cpu*
  - mbuild
  - numpy
  - pip
  - python
  - matplotlib
  - pymbar >= 4.0
  - rowan
