FROM mambaorg/micromamba:0.15.2

USER root

ADD . /cmeutils

WORKDIR /cmeutils

RUN micromamba install -y -n base -f environment.yml && \
    micromamba clean --all --yes && \
    pip install install -e .

WORKDIR /home
